# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b91c9f9ee7d547f27fe75d99b33432a8fbc2bcceeac6914cd1c7a275642a9006c7a2ce4e1d69d4b26e8ffe6c2d070a6791ef1a8f6c9036ebe0bedf047e07d653

test:
  secret_key_base: 667add0d0437718e7ae2f07c85a58b51085512fe0abe5e3fd1ee11fcf0fc4aaa3a9da29167d2eb4cc49b0487d9872885d4e41586b705e2ea9a45d7b1266b73b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
